verbose: false
instrumentation:
  root: lib/
  excludes:
    - lib/test-fixture.js
    - lib/test/
  include-all-sources: false
reporting:
  print: summary
  reports:
    - html
    - text
    - lcov
  watermarks:
    statements: [70, 90]
    lines: [70, 90]
    functions: [70, 90]
    branches: [70, 90]